definitions:
  model.AuthUser:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  model.Book:
    properties:
      author:
        type: string
      id:
        type: integer
      price:
        type: number
      title:
        type: string
    type: object
  model.BookReq:
    properties:
      author:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
  model.CurrentBooks:
    properties:
      book:
        $ref: '#/definitions/model.Book'
      sum:
        type: number
    type: object
  model.IncrementBalanceReq:
    properties:
      amount:
        type: integer
      user_id:
        type: integer
    type: object
  model.PasswordReq:
    properties:
      old_password:
        type: string
      password:
        type: string
    type: object
  model.Transaction:
    properties:
      ID:
        type: integer
      amount:
        type: number
      book_id:
        type: integer
      created_at:
        type: string
      deleted_at:
        type: string
      user_id:
        type: integer
    type: object
  model.TransactionReq:
    properties:
      amount:
        type: number
      book_id:
        type: integer
      user_id:
        type: integer
    type: object
  model.User:
    properties:
      ID:
        type: integer
      balance:
        type: number
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      photo_URL:
        type: string
      username:
        type: string
    type: object
  model.UserBorrow:
    properties:
      books:
        items:
          $ref: '#/definitions/model.Book'
        type: array
      user:
        $ref: '#/definitions/model.User'
    type: object
  model.UserCreateReq:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: Auth get JWT token
      operationId: AuthUser
      parameters:
      - description: Входящие данные
        in: body
        name: rq
        required: true
        schema:
          $ref: '#/definitions/model.AuthUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Auth get JWT token
      tags:
      - user
  /balance:
    post:
      consumes:
      - application/json
      description: Increment Balance
      operationId: IncrementBalance
      parameters:
      - description: Входящие данные
        in: body
        name: rq
        required: true
        schema:
          $ref: '#/definitions/model.IncrementBalanceReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Increment Balance
      tags:
      - transaction
  /book:
    get:
      consumes:
      - application/json
      description: Get all Book
      operationId: GetAllBook
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get all Book
      tags:
      - book
    post:
      consumes:
      - application/json
      description: Create Book
      operationId: CreateBook
      parameters:
      - description: Входящие данные
        in: body
        name: rq
        required: true
        schema:
          $ref: '#/definitions/model.BookReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create Book
      tags:
      - book
  /getLastMonthly:
    get:
      consumes:
      - application/json
      description: Get Books borrowed last month
      operationId: Get Books borrowed last month
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.UserBorrow'
            type: array
      summary: Get Books borrowed last month
      tags:
      - borrow
  /getNotReturned:
    get:
      consumes:
      - application/json
      description: Get not Returned books for user
      operationId: Get not Returned books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.UserBorrow'
            type: array
      summary: Get not Returned books for user
      tags:
      - borrow
  /getNotReturnedSum:
    get:
      consumes:
      - application/json
      description: Get not Returned books with sum
      operationId: Get not Returned books wtih sum
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.CurrentBooks'
            type: array
      summary: Get not Returned books with sum
      tags:
      - borrow
  /transaction:
    delete:
      consumes:
      - application/json
      description: Cancel Transaction
      operationId: CamcelTransaction
      parameters:
      - description: Входящие данные
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Cancel Transaction
      tags:
      - transaction
    post:
      consumes:
      - application/json
      description: Create Transaction
      operationId: CreateTransaction
      parameters:
      - description: Входящие данные
        in: body
        name: rq
        required: true
        schema:
          $ref: '#/definitions/model.TransactionReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Transaction'
      summary: Create Transaction
      tags:
      - transaction
  /user:
    get:
      consumes:
      - application/json
      description: Get User
      operationId: GetUser
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      security:
      - ApiKeyAuth: []
      summary: Get User
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Создание пользователя
      operationId: CreateUser
      parameters:
      - description: Входящие данные
        in: body
        name: rq
        required: true
        schema:
          $ref: '#/definitions/model.UserCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Создание пользователя
      tags:
      - user
  /user/password:
    post:
      consumes:
      - application/json
      description: Change Passowrd for user
      operationId: ChangePassword
      parameters:
      - description: Входящие данные
        in: body
        name: rq
        required: true
        schema:
          $ref: '#/definitions/model.PasswordReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      security:
      - ApiKeyAuth: []
      summary: Change Password for user
      tags:
      - user
swagger: "2.0"
