run:
  timeout: 3m
  skip-dirs:
    - build/
    - configs/
    - logs/
    - migrations/
output:
  sort-results: true
issues:
  exclude-rules:
    - linters:
        - varnamelen
      text: "is too short for the scope of its usage"
    - linters:
        - revive
      text: "parameter 'ctx' seems to be unused, consider removing or renaming it as"
linters:
  disable-all: true
  enable:
    - errcheck
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - stylecheck
    - staticcheck
    - typecheck
    - unused
    - wsl
